WarehouseSystem/Controllers/RFIDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WarehouseSystem.Models;
using WarehouseSystem.Models.ViewModel;
using WarehouseSystem.Service.Interface;

namespace WarehouseSystem.Controllers
{
    [AuthorizeUser]
    public class RFIDController : Controller
    {
        private IRFIDService m_RFIDService;

        public RFIDController(IRFIDService p_RFIDService)
        {
            m_RFIDService = p_RFIDService;
        }

        public ActionResult Create()
        {
            RFIDViewModel _RFIDViewModel = new RFIDViewModel();

            return View(_RFIDViewModel);
        }

        [HttpPost]
        public ActionResult CreateRFID(string RFIDNumber)
        {
            string RFIDID = "";

            var Result = m_RFIDService.Create(RFIDNumber, ref RFIDID);

            if (Result.Success)
            {
                return RedirectToAction("Edit", new { RFIDID = RFIDID });
            }
            else
            {
                RFIDViewModel _RFIDViewModel = new RFIDViewModel()
                {
                    ErrorMessage = Result.Message
                };

                return View("Create", _RFIDViewModel);
            }
        }

        public ActionResult Edit(string RFIDID)
        {
            if (string.IsNullOrEmpty(RFIDID))
            {
                return RedirectToAction("List");
            }
            else
            {
                var RFID = m_RFIDService.GetBySID(RFIDID);

                if (RFID != null)
                {
                    RFIDViewModel _RFIDViewModel = new RFIDViewModel()
                    {
                        RFID = RFID
                    };
                    return View(_RFIDViewModel);
                }
                else return RedirectToAction("List");
            }
        }

        [HttpPost]
        public ActionResult Update(JsonType _JsonType)
        {
            var pResult = m_RFIDService.Update(_JsonType.pk, _JsonType.Name, _JsonType.Value);

            return Json(new { Result = pResult });
            //if (pResult.Success)
            //{
                
            //}
            //else return RedirectToAction("List");
        }

        public ActionResult Delete(string RFIDID)
        {
            if (!string.IsNullOrEmpty(RFIDID))
            {
                var pResult = m_RFIDService.Delete(RFIDID);
                return Json(new { Result = pResult.Success });
            }

            return Json(new { Result = false });
            //return RedirectToAction("List");
        }

        public ActionResult List(string MainMenu, string SubMenu, string MinorMenu)
        {
            UpdateSession(MainMenu, SubMenu, MinorMenu);

            var RFIDList = m_RFIDService.GetAll().ToList();

            List<RFIDViewModel> RFIDViewModelList = new List<RFIDViewModel>();

            foreach (var RFID in RFIDList)
            {
                RFIDViewModelList.Add(new RFIDViewModel()
                {
                    RFID = RFID
                });
            }

            return View(RFIDViewModelList);
        }

        private void UpdateSession(string MainMenu, string SubMenu, string MinorMenu)
        {
            Session["MainMenu"] = MainMenu;
            Session["SubMenu"] = SubMenu;
            Session["MinorMenu"] = MinorMenu;
        }
    }
}

WarehouseSystem/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WarehouseSystem;
using WarehouseSystem.Models;
using WarehouseSystem.Service.Interface;
using WarehouseSystem.Service;
using WarehouseSystem.Models.ViewModel;
using WarehouseSystem.Service.Misc;
using System.Web.Security;

namespace WarehouseSystem.Controllers
{
    [AuthorizeUser]
    public class UserController : Controller
    {
        private IUserService m_UserService;
        private IUserGroupService m_UserGroupService;

        public UserController(IUserService pUserService, IUserGroupService pUserGroupService)
        {
            m_UserService = pUserService;
            m_UserGroupService = pUserGroupService;
        }

        public ActionResult Create()
        {
            UserViewModel pUserViewModel = new UserViewModel();

            return View(pUserViewModel);
        }

        [HttpPost]
        public ActionResult CreateUserProfile(string UserID, string Password, string ConfirmPassword)
        {
            UserViewModel pUserViewModel = new UserViewModel();

            if (!string.IsNullOrEmpty(UserID) &&
                !string.IsNullOrEmpty(Password) &&
                !string.IsNullOrEmpty(ConfirmPassword) &&
                ModelState.IsValid)
            {
                //確認密碼是否一致
                if (Password == ConfirmPassword)
                {
                    string UserProfileID = "";

                    var pResult = m_UserService.Create(UserID, Password, ref UserProfileID);

                    if (pResult.Success == false)
                    {
                        pUserViewModel.UserProfile.UserID = UserID;
                        pUserViewModel.UserProfile.Password = Password;
                        pUserViewModel.ErrorMessage = pResult.Message;

                        return View("Create", pUserViewModel);
                    }
                    else
                    {
                        return RedirectToAction("Edit");
                    }
                }
                else
                {
                    pUserViewModel.UserProfile.UserID = UserID;
                    pUserViewModel.UserProfile.Password = Password;
                    pUserViewModel.ErrorMessage = "確認密碼不一致";
                }
            }
            else
            {
                pUserViewModel.UserProfile.UserID = UserID;
                pUserViewModel.UserProfile.Password = Password;
                pUserViewModel.ErrorMessage = "Email空白或密碼空白";
            }

            return View("Create", pUserViewModel);
        }


        public ActionResult Edit(string UserProfileID)
        {
            if (string.IsNullOrEmpty(UserProfileID))
            {
                return RedirectToAction("List");
            }
            else
            {
                var UserProfile = m_UserService.GetBySID(UserProfileID);
                var UserGroup = m_UserGroupService.GetAll().ToList();
                var UserGroupName = UserGroup.Where(e => e.UserGroupID == UserProfile.UserGroupID).ToList();

                UserViewModel pUserViewModel = new UserViewModel()
                {
                    UserProfile = UserProfile,
                    UserGroup = UserGroup,
                    UserGroupName = (UserGroupName.Count > 0) ? UserGroupName[0].GroupName : "",
                    ErrorMessage = ""
                };

                return View(pUserViewModel);
            }
        }
        public ActionResult DefaultEdit(string MainMenu, string SubMenu, string MinorMenu)
        {
            UpdateSession(MainMenu, SubMenu, MinorMenu);

            FormsIdentity id = (FormsIdentity)User.Identity;
            FormsAuthenticationTicket ticket = id.Ticket;
            var userData = ticket.UserData.Split(',');
            
            string UserProfileID = userData[0];

            if (string.IsNullOrEmpty(UserProfileID))
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                var UserProfile = m_UserService.GetBySID(UserProfileID);
                var UserGroup = m_UserGroupService.GetAll().ToList();
                var UserGroupName = UserGroup.Where(e => e.UserGroupID == UserProfile.UserGroupID).ToList();

                UserViewModel pUserViewModel = new UserViewModel()
                {
                    UserProfile = UserProfile,
                    UserGroup = UserGroup,
                    UserGroupName = (UserGroupName.Count > 0) ? UserGroupName[0].GroupName : "",
                    ErrorMessage = ""
                };

                return View(pUserViewModel);
            }
        }

        [HttpPost]
        public ActionResult Update(JsonType _JsonType)
        {
            var pResult = m_UserService.Update(_JsonType.pk, _JsonType.Name, _JsonType.Value);

            return Json(new { Result = pResult });

            //if (pResult.Success)
            //{
            //    var User = m_UserGroupService.GetBySID(_JsonType.pk);

            //    return Json(new { User = User });
            //}
            //else return RedirectToAction("List");
        }

        public ActionResult Delete(string UserProfileID)
        {
            if (!string.IsNullOrEmpty(UserProfileID))
            {
                if (m_UserService.IsExists(UserProfileID))
                {
                    var pResult = m_UserService.Delete(UserProfileID);
                    return Json(new { Result = pResult.Success });
                }
            }
            return Json(new { Result = false });
        }

        public ActionResult List(string MainMenu, string SubMenu, string MinorMenu)
        {
            UpdateSession(MainMenu, SubMenu, MinorMenu);

            var UserProfileList = m_UserService.GetAll().ToList();

            List<UserViewModel> UserViewModelList = new List<UserViewModel>();

            foreach (var UserProfile in UserProfileList)
            {
                UserViewModelList.Add(new UserViewModel()
                {
                    UserProfile = UserProfile
                });
            }

            return View(UserViewModelList);
        }

        public ActionResult ModifyPassword(string MainMenu, string SubMenu, string MinorMenu)
        {
            UpdateSession(MainMenu, SubMenu, MinorMenu);

            if (System.Web.HttpContext.Current.User.Identity.IsAuthenticated == true)
            {
                FormsIdentity id = (FormsIdentity)User.Identity;
                FormsAuthenticationTicket ticket = id.Ticket;

                var userData = ticket.UserData.Split(',');

                CST_USER_PROFILE UserProfile = new CST_USER_PROFILE()
                {
                    UserProfileID = userData[0]
                };

                UserViewModel _UserViewModel = new UserViewModel()
                {
                    UserProfile = UserProfile
                };

                return View(_UserViewModel);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult ChangePassword(string Password, string ModifyPassword, string UserProfileID)
        {
            var Result = m_UserService.ChangePassword(Password, ModifyPassword, UserProfileID);

            if (Result.Success)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                UserViewModel _UserViewModel = new UserViewModel()
                {
                    UserProfile = new CST_USER_PROFILE() { UserProfileID = UserProfileID },
                    ErrorMessage = Result.Message
                };

                return View("ModifyPassword", _UserViewModel);
            }
        }

        [AllowAnonymous]
        public ActionResult Login()
        {
            //使用者登出
            FormsAuthentication.SignOut();

            //清除所有的 session
            Session.RemoveAll();

            //建立一個同名的 Cookie 來覆蓋原本的 Cookie
            HttpCookie cookie1 = new HttpCookie(FormsAuthentication.FormsCookieName, "");
            cookie1.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie1);

            //建立 ASP.NET 的 Session Cookie 同樣是為了覆蓋
            HttpCookie cookie2 = new HttpCookie("ASP.NET_SessionId", "");
            cookie2.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie2);

            //Session.Clear();
            Session.Abandon();

            UserViewModel _UserViewModel = new UserViewModel();

            return View(_UserViewModel);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(string UserID, string Password)
        {
            var pUserProfile = m_UserService.Login(UserID, Password);

            if (string.IsNullOrEmpty(pUserProfile.ErrorMessage))
            {
                //使用MVC內建登入並利用自訂權限[AuthorizeUser]功能
                LoginProcess(pUserProfile.UserProfile, false);
                SettingMenuHtml(pUserProfile.UserProfile.UserGroupID);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                pUserProfile.UserProfile = new CST_USER_PROFILE();

                return View(pUserProfile);
            }
        }

        [AllowAnonymous]
        public ActionResult Logout()
        {
            //使用者登出
            FormsAuthentication.SignOut();

            //清除所有的 session
            Session.RemoveAll();

            //建立一個同名的 Cookie 來覆蓋原本的 Cookie
            HttpCookie cookie1 = new HttpCookie(FormsAuthentication.FormsCookieName, "");
            cookie1.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie1);

            //建立 ASP.NET 的 Session Cookie 同樣是為了覆蓋

WarehouseSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Html.Partial("resource")

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        @Html.Partial("header")
        @Html.Partial("_menu")
        @RenderBody()
        @RenderSection("scripts", required: false)
        @Html.Partial("footer")
    </div>
</body>

WarehouseSystem/Views/Shared/_menu.cshtml
<script>
    var MainMenu = '@Session["MainMenu"]';
    var SubMenu = '@Session["SubMenu"]';
    var MinorMenu = '@Session["MinorMenu"]';

    $(document).ready(function () {
        if (MainMenu != '' || MainMenu != null) $('#' + MainMenu).addClass('active treeview');
        if (SubMenu != '' || SubMenu != null) $('#' + SubMenu).addClass('active treeview');
        if (MinorMenu != '' || MinorMenu != null) $('#' + MinorMenu).addClass('active');
    });

</script>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
           @if (Context.User.Identity.IsAuthenticated == true)
           { 
                <li class="header" style="color:#FFFFFF; font-size: 24px;">功 能 列 表</li>
                @Html.Raw(Session["HtmlString"])
           }
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

WarehouseSystem/Views/Shared/footer.cshtml
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; 2017-2025 <a href="#"> POS SYSTEM </a>.</strong> All rights reserved.
</footer>

WarehouseSystem/Views/Shared/header.cshtml
<header class="main-header">
    <!-- Logo -->
    <div class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><img src="../../Images/POS.png" style="width: 70%;"></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><img src="../../Images/POS.png" style="width: 20%;">POS!!!</span>
    </div>

    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Sidebar toggle button-->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
               @if (Context.User.Identity.IsAuthenticated == true)
                {
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="../../Images/POS.png" class="user-image" alt="User Image">
                            <span class="hidden-xs">@Context.User.Identity.Name</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-right">
                                    <a href="@Url.Action("Logout", "User")" class="btn btn-default btn-flat">登出</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                }
            </ul>
        </div>
    </nav>
</header>

WarehouseSystem/Views/Shared/menu.cshtml
<script>
    var MainMenu = '@Session["MainMenu"]';
    var SubMenu = '@Session["SubMenu"]';
    var MinorMenu = '@Session["MinorMenu"]';

    $(document).ready(function () {
        if (MainMenu != '' || MainMenu != null) $('#' + MainMenu).addClass('active treeview');
        if (SubMenu != '' || SubMenu != null) $('#' + SubMenu).addClass('active treeview');
        if (MinorMenu != '' || MinorMenu != null) $('#' + MinorMenu).addClass('active');
    });

</script>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        @if (Context.User.Identity.IsAuthenticated == false)
        {
        <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu">
                <li class="header" style="color:#FFFFFF; font-size: 24px;">功 能 列 表</li>
                    <li class="treeview">

            <a href="#"><i class="fa fa-dashboard"></i> <span>選單管理</span> <i class="fa fa-angle-left pull-right"></i></a>
            <ul class="treeview-menu">
                <li class="treeview">
                    <a href="@Url.Action("TEST", "UserGroup")"><i class="fa fa-edit"></i> <span>主選單管理</span> <i class="fa fa-angle-left pull-right"></i></a>
                </li>
                <li class="treeview">
                    <a href="#"><i class="fa fa-edit"></i> <span>子選單管理</span> <i class="fa fa-angle-left pull-right"></i></a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="@Url.Action("Create", "MainMenu")"><i class="fa fa-circle-o"></i>新增子主選單</a>
                        </li>
                        <li>
                            <a href="@Url.Action("List", "MainMenu")"><i class="fa fa-circle-o"></i>子選單列表</a>
                        </li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#"><i class="fa fa-edit"></i> <span>次選單管理</span> <i class="fa fa-angle-left pull-right"></i></a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="@Url.Action("Create", "MainMenu")"><i class="fa fa-circle-o"></i>新增次選單</a>
                        </li>
                        <li>
                            <a href="@Url.Action("List", "MainMenu")"><i class="fa fa-circle-o"></i>次選單列表</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
                <li class="treeview" id="T1">
                    <a href="#"><i class="fa fa-dashboard"></i> <span>系統管理</span> <i class="fa fa-angle-left pull-right"></i></a>
                    <ul class="treeview-menu">
                        <li class="treeview">
                            <a href="#"><i class="fa fa-edit"></i> <span>帳號管理</span> <i class="fa fa-angle-left pull-right"></i></a>
                            <ul class="treeview-menu">
                                <li class="">
                                    <a href="@Url.Action("Create", "User")"><i class="fa fa-circle-o"></i>帳號列表</a>
                                </li>
                                <li>
                                    @*<a href="@Url.Action("List", "User")"><i class="fa fa-circle-o"></i>帳號列表</a>*@
                                    <a href="@Url.Content("/User/List?MinorMenu=T3")"><i class="fa fa-circle-o"></i>帳號列表</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("List", "User")"><i class="fa fa-circle-o"></i>權限列表</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("List", "User")"><i class="fa fa-circle-o"></i>修改密碼</a>
                                </li>
                            </ul>
                        </li>
                        <li class="treeview">
                            <a href="#"><i class="fa fa-edit"></i> <span>棧板管理</span> <i class="fa fa-angle-left pull-right"></i></a>
                            <ul class="treeview-menu">
                                <li>
                                    <a href="@Url.Action("PalletTypeCreate", "Pallet")"><i class="fa fa-circle-o"></i>新增棧板類別</a>
                                </li>
                                <li>
                                    <a href="@Url.Content("/Pallet/PalletTypeEdit?MainMenu=333&SubMenu=111&MinorMenu=22")"><i class="fa fa-circle-o"></i>棧板類別管理</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("PalletCreate", "Pallet")"><i class="fa fa-circle-o"></i>新增棧板資料</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("PalletList", "Pallet")"><i class="fa fa-circle-o"></i>棧板資料管理</a>
                                </li>
                            </ul>
                            <a href="#"><i class="fa fa-edit"></i> <span>警示管理</span> <i class="fa fa-angle-left pull-right"></i></a>
                            <ul class="treeview-menu"></ul>
                        </li>
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#"><i class="fa fa-dashboard"></i> <span>圖資管理</span> <i class="fa fa-angle-left pull-right"></i></a>
                    <ul class="treeview-menu">
                        <li class="treeview">
                            @*<a href="#"><i class="fa fa-edit"></i> <span>定位管理</span> <i class="fa fa-angle-left pull-right"></i></a>
                                <ul class="treeview-menu">
                                    <li>
                                        <a href="@Url.Action("Add", "Card")"><i class="fa fa-circle-o"></i>新增定位卡</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("List", "Card")"><i class="fa fa-circle-o"></i>定位卡管理</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Add", "Card")"><i class="fa fa-circle-o"></i>新增定位接收器</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("List", "Card")"><i class="fa fa-circle-o"></i>定位接收器管理</a>
                                    </li>
                                </ul>*@
                        </li>
                        <li class="treeview">
                            <a href="#"><i class="fa fa-edit"></i> <span>RFID管理</span> <i class="fa fa-angle-left pull-right"></i></a>
                            <ul class="treeview-menu">
                                <li>
                                    <a href="@Url.Action("Create", "RFID")"><i class="fa fa-circle-o"></i>新增RFID卡</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("List", "RFID")"><i class="fa fa-circle-o"></i>RFID卡管理</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Create", "GateReader")"><i class="fa fa-circle-o"></i>新增RFID接收器</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("List", "GateReader")"><i class="fa fa-circle-o"></i>RFID接收器管理</a>
                                </li>
                            </ul>
                        </li>
                        <li class="treeview">
                            <a href="#"><i class="fa fa-edit"></i> <span>儲位管理</span> <i class="fa fa-angle-left pull-right"></i></a>
                            <ul class="treeview-menu">
                                <li>
                                    <a href="@Url.Action("Add", "Field")"><i class="fa fa-circle-o"></i>新增儲位域區</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("List", "Field")"><i class="fa fa-circle-o"></i>儲位場區管理</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#"><i class="fa fa-dashboard"></i> <span>查詢管理</span> <i class="fa fa-angle-left pull-right"></i></a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="@Url.Action("trackingMap", "tracking")"><i class="fa fa-circle-o"></i>棧板查詢</a>
                        </li>
                        <li>
                            <a href="@Url.Action("trackingCart", "tracking")"><i class="fa fa-circle-o"></i>Log查詢</a>
                        </li>
                        <li>
                            @*<a href="@Url.Action("trackingTrajectory", "tracking")"><i class="fa fa-circle-o"></i>軌跡回放</a>*@
                        </li>
                    </ul>
                </li>
            </ul>
        }

    </section>
    <!-- /.sidebar -->
</aside>

WarehouseSystem/Views/Shared/resource.cshtml
@{
    Layout = null;
}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>巨宣-POS</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

<!-- Bootstrap 3.3.5 -->
<link rel="stylesheet" href="../../theme/AdminLTE/bootstrap/css/bootstrap.min.css">

<!-- Theme style -->
<link rel="stylesheet" href="../../theme/AdminLTE/dist/css/AdminLTE.min.css">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="../../theme/AdminLTE/dist/css/skins/_all-skins.min.css">

<link rel="stylesheet" href="../../theme/AdminLTE/plugins/datatables/jquery.dataTables.min.css">

<link rel="stylesheet" href="../../theme/AdminLTE/plugins/datatables/dataTables.bootstrap.css">